eureka:
  instance:
    leaseExpirationDurationInSeconds: 30
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 15